import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from "@/components/shared/Navbar"
import { ClerkProvider } from '@clerk/nextjs'
import Footer from '@/components/shared/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Evently',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>


    <html lang="en">
      <body className={inter.className}>

    <div>

        {children}
          </div>
   
      </body>
      </html>
      </ClerkProvider>
  )
}
